# Generated by Django 3.2 on 2023-05-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_auto_20230412_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
