# Generated by Django 3.2 on 2023-03-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_engine', '0002_auto_20230328_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_on']},
        ),
    ]
