# Generated by Django 3.2 on 2023-03-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_engine', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
    ]
