# Generated by Django 3.2 on 2023-03-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_engine', '0004_alter_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Image',
            new_name='item_image',
        ),
    ]
