# Generated by Django 3.2 on 2023-03-31 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_engine', '0005_rename_image_item_item_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='created_by',
        ),
    ]
